### ISSUE TITLE
[로그인 및 회원가입 페이지] 마크업 및 스타일링

### ISSUE THREAD

**Issue by ryudg** [LionPlace/JS-LionPlace#14]

**Comment by h2s0** [comment]
![image](https://github.com/LionPlace/JS-LionPlace/assets/134567479/b5ffccf2-d9af-4751-bea3-908e77097620)
![image](https://github.com/LionPlace/JS-LionPlace/assets/134567479/98ab5408-d210-4d33-ba49-2f3ad0f89222)
![image](https://github.com/LionPlace/JS-LionPlace/assets/134567479/a40eee6a-e7cc-426d-8bc1-0a65c1ca9f58)

**Comment by h2s0** [comment]
![image](https://github.com/LionPlace/JS-LionPlace/assets/134567479/04d9330a-b245-463e-beab-93805db29652)

validation check 결과, 로그인, 회원가입 페이지에서 로그인 입력 창의 type 때문에 오류가 발생하였습니다.
type 을 id에서 text 값으로 바꿔주었습니다.
